#!/usr/bin/env bash
set -o errexit
# ==============================================================================
# workflow-unset-commit-template
# Author: Connor de la Cruz (connor.c.delacruz@gmail.com)
# ------------------------------------------------------------------------------
# For use with commit-template.sh
#
# Unset branch's git config for commit.template. Template file will be deleted
# unless -D argument was specified.
#
# ------------------------------------------------------------------------------
# Usage
# ------------------------------------------------------------------------------
# Usage: workflow-unset-commit-template [-b <branch>] [-D] [-h]
#
# This script accepts optional arguments to override defaults. For details on
# optional arguments, run:
#
#   workflow-unset-commit-template -h
#
# ==============================================================================

# Imports ----------------------------------------------------------------------
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
readonly UTIL_DIR="$SCRIPT_DIR/util"
source "$UTIL_DIR/ALL.sh"

# Functions --------------------------------------------------------------------

show_help() {
    echo "Usage: workflow-unset-commit-template [-b <branch>] [-D] [-h]"
    echo "Options:"
    echo "  -b <branch>  Specify branch to unset template for (default: current branch)."
    echo "  -D           Don't delete commit template file."
    echo "  -h           Show this help message and exit."
}

# Main -------------------------------------------------------------------------

# Checks the local commit.template config for the current repo. If configured,
# will unset and delete the template file it was set to.
#
# Arguments:
#   Takes all optional arguments for script. For details on these arguments,
#   see show_help()
main() {
    # Parse arguments:
    # -D don't delete template file
    # -b <branch> unset a different branch
    local arg_no_delete arg_branch_name
    while getopts 'Db:h' opt; do
        case ${opt} in
            D)
                arg_no_delete=1
                ;;
            b)
                arg_branch_name="$OPTARG"
                ;;
            h|?)
                show_help
                [[ "$opt" = "?" ]] && local exit_code=1 || local exit_code=0
                exit $exit_code
                ;;
        esac
    done
    shift $((OPTIND -1))

    # Check git version > 2.23 and that we're in a repo currently
    local version_check="$(verify_git_version)"
    [[ -n "$version_check" ]] && error "$version_check" && exit 1
    verify_git_repo

    # Get current branch and assiociated config
    local branch_name="${arg_branch_name:-$(git_current_branch)}"
    local branch_config_file="$(git config --local --includes --get includeif.onbranch:${branch_name}.path)"
    [[ -z "$branch_config_file" ]] && echo "No config file specified for branch $branch_name." && exit
    local repo_root_dir="$(git_repo_root)"
    # TODO check if initialized, otherwise use --show-origin to find the target file?
    local workflow_config_path="$(git config --local --includes --get workflow.configpath)"
    local branch_config_path="$repo_root_dir/.git/$branch_config_file"
    local commit_template_file="$(git config -f "$branch_config_path" --get commit.template)"
    local commit_template_path="$repo_root_dir/$commit_template_file"

    # Unset branch config
    echo "Unsetting branch config include..."
    git config -f "$workflow_config_path" --unset includeIf.onbranch:${branch_name}.path
    success "Local repo updated." \
            "Will no longer include configs from .git/$branch_config_file" \
            "when on branch $branch_name."
    echo "Deleting branch config file .git/$branch_config_file..."
    rm "$branch_config_path"
    success "Branch config file removed."

    # Delete commit template (unless -D was specified)
    if [[ -z "$commit_template_file" ]]; then
        warning "Template file $commit_template_file not found."
        exit
    fi
    if [[ -n "$arg_no_delete" ]]; then
        warning "-D was specified, leaving template file $commit_template_file."
    else
        echo "Removing commit template file $commit_template_file..."
        rm "$commit_template_path"
        success "Removed $commit_template_path"
    fi
}
main "$@"
