#!/usr/bin/env bash
set -o errexit
# ==============================================================================
# workflow-init
# Author: Connor de la Cruz (connor.c.delacruz@gmail.com)
# ------------------------------------------------------------------------------
# Set up the git repository for use with workflow scripts.
#
# NOTE: Scripts that depend on the workflow config set up should run this
# script automagically if the current repo has not been initialized, so you
# probably won't ever need to run this directly.
#
# ------------------------------------------------------------------------------
# Details
# ------------------------------------------------------------------------------
# 1. Create .git/config_workflow. Any configurations made by other workflow
#    scripts will be set in this file.
# 2. Add include.path=config_workflow to local repo config. This will pull in
#    any configurations from that file into the local repo.
# ==============================================================================

# Imports ----------------------------------------------------------------------
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
readonly UTIL_DIR="$SCRIPT_DIR/util"
source "$UTIL_DIR/ALL.sh"

# Main -------------------------------------------------------------------------

main() {
    # Check git version > 2.23 and that we're in a repo currently
    local version_check="$(verify_git_version)"
    [[ -n "$version_check" ]] && error "$version_check" && exit 1
    verify_git_repo

    [[ "$(is_workflow_configured)" > 0 ]] && echo "Repo already initialized." && exit

    local repo_root_dir="$(git_repo_root)"
    local workflow_config_path="$repo_root_dir/.git/config_workflow"
    echo "Creating workflow config file for this repo..."
    git config -f "$workflow_config_path" workflow.configpath "$workflow_config_path"
    if [[ "$(verify_workflow_config_file "$repo_root_dir")" > 0 ]]; then
        success "Workflow config created:" \
                "$workflow_config_path"
    else
        error "Unable to create workflow config at the following path:" \
              "$workflow_config_path"
        exit 1
    fi
    # It may be possible that the config file was deleted but the include.path
    # value was still present in local git config. To avoid adding duplicate
    # entries, check for the include before updating configurations
    if [[ "$(verify_workflow_config_include)" < 1 ]]; then
        echo "Updating local config..."
        git config --local --add include.path config_workflow
    fi
    # Regardless of whether the config was updated above or not, we want to
    # check again here before displaying the success message
    if [[ "$(verify_workflow_config_include)" > 0 ]]; then
        success "Repo configured. Initialization complete."
    else
        error "Something went wrong when adding include.path for workflow config to local repo."
        exit 1
    fi
}
main "$@"
